module.exports = function usersCollection(){
    return [{
        "id": 1,
        "name": "test",
        "password": "1234567",
        "email": "test@test.ru",
        "avatar": "https://usgs.gov/enim/blandit/mi/in/porttitor/pede.aspx?in=congue&faucibus=vivamus&orci=metus&luctus=arcu&et=adipiscing&ultrices=molestie&posuere=hendrerit&cubilia=at&curae=vulputate&nulla=vitae&dapibus=nisl&dolor=aenean&vel=lectus&est=pellentesque&donec=eget&odio=nunc&justo=donec&sollicitudin=quis",
        "timeZone": "59630-115",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 2,
        "name": "Judson",
        "password": "25-003-4214",
        "email": "djudson1@pbs.org",
        "avatar": "http://yale.edu/ut/suscipit/a.json?platea=ipsum&dictumst=dolor&aliquam=sit&augue=amet&quam=consectetuer&sollicitudin=adipiscing&vitae=elit&consectetuer=proin&eget=interdum&rutrum=mauris&at=non&lorem=ligula&integer=pellentesque&tincidunt=ultrices&ante=phasellus&vel=id&ipsum=sapien",
        "timeZone": "0440-1736",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 3,
        "name": "Lorens",
        "password": "21-061-9223",
        "email": "alorens2@imgur.com",
        "avatar": "https://feedburner.com/neque/sapien/placerat.jpg?ligula=vulputate&pellentesque=justo&ultrices=in&phasellus=blandit&id=ultrices&sapien=enim&in=lorem&sapien=ipsum&iaculis=dolor&congue=sit&vivamus=amet&metus=consectetuer&arcu=adipiscing&adipiscing=elit&molestie=proin&hendrerit=interdum&at=mauris&vulputate=non&vitae=ligula&nisl=pellentesque&aenean=ultrices&lectus=phasellus&pellentesque=id&eget=sapien&nunc=in&donec=sapien&quis=iaculis&orci=congue&eget=vivamus&orci=metus&vehicula=arcu&condimentum=adipiscing&curabitur=molestie&in=hendrerit&libero=at&ut=vulputate&massa=vitae&volutpat=nisl&convallis=aenean&morbi=lectus&odio=pellentesque&odio=eget&elementum=nunc&eu=donec&interdum=quis&eu=orci&tincidunt=eget&in=orci",
        "timeZone": "63347-501",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 4,
        "name": "Mansuer",
        "password": "23-254-5658",
        "email": "gmansuer3@cdbaby.com",
        "avatar": "https://jigsy.com/erat.aspx?quam=orci&fringilla=nullam&rhoncus=molestie&mauris=nibh&enim=in&leo=lectus&rhoncus=pellentesque&sed=at&vestibulum=nulla&sit=suspendisse&amet=potenti&cursus=cras&id=in&turpis=purus&integer=eu&aliquet=magna&massa=vulputate&id=luctus&lobortis=cum&convallis=sociis&tortor=natoque&risus=penatibus&dapibus=et&augue=magnis&vel=dis&accumsan=parturient&tellus=montes&nisi=nascetur&eu=ridiculus&orci=mus&mauris=vivamus&lacinia=vestibulum&sapien=sagittis&quis=sapien&libero=cum&nullam=sociis&sit=natoque&amet=penatibus&turpis=et&elementum=magnis&ligula=dis&vehicula=parturient&consequat=montes&morbi=nascetur&a=ridiculus&ipsum=mus&integer=etiam&a=vel&nibh=augue&in=vestibulum&quis=rutrum&justo=rutrum&maecenas=neque&rhoncus=aenean&aliquam=auctor&lacus=gravida&morbi=sem&quis=praesent&tortor=id&id=massa&nulla=id&ultrices=nisl&aliquet=venenatis&maecenas=lacinia&leo=aenean&odio=sit&condimentum=amet&id=justo&luctus=morbi&nec=ut&molestie=odio&sed=cras&justo=mi&pellentesque=pede&viverra=malesuada&pede=in&ac=imperdiet&diam=et&cras=commodo&pellentesque=vulputate&volutpat=justo&dui=in&maecenas=blandit&tristique=ultrices&est=enim&et=lorem",
        "timeZone": "63187-104",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 5,
        "name": "Delacroux",
        "password": "89-416-2891",
        "email": "ndelacroux4@nsw.gov.au",
        "avatar": "http://google.co.uk/magna/at/nunc/commodo/placerat/praesent.jsp?nec=vel&dui=nisl&luctus=duis&rutrum=ac&nulla=nibh&tellus=fusce&in=lacus&sagittis=purus&dui=aliquet&vel=at&nisl=feugiat&duis=non&ac=pretium&nibh=quis&fusce=lectus&lacus=suspendisse&purus=potenti&aliquet=in&at=eleifend&feugiat=quam&non=a&pretium=odio&quis=in&lectus=hac&suspendisse=habitasse&potenti=platea&in=dictumst&eleifend=maecenas&quam=ut&a=massa&odio=quis&in=augue&hac=luctus&habitasse=tincidunt&platea=nulla&dictumst=mollis&maecenas=molestie&ut=lorem&massa=quisque&quis=ut&augue=erat&luctus=curabitur&tincidunt=gravida&nulla=nisi&mollis=at&molestie=nibh",
        "timeZone": "76071-2001",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 6,
        "name": "Jiras",
        "password": "23-799-6355",
        "email": "jjiras5@networkadvertising.org",
        "avatar": "http://theglobeandmail.com/in/faucibus/orci/luctus/et/ultrices/posuere.json?felis=viverra&eu=pede&sapien=ac&cursus=diam&vestibulum=cras&proin=pellentesque&eu=volutpat&mi=dui&nulla=maecenas&ac=tristique&enim=est&in=et&tempor=tempus&turpis=semper&nec=est&euismod=quam&scelerisque=pharetra&quam=magna&turpis=ac&adipiscing=consequat&lorem=metus&vitae=sapien&mattis=ut&nibh=nunc&ligula=vestibulum&nec=ante&sem=ipsum&duis=primis&aliquam=in&convallis=faucibus&nunc=orci&proin=luctus&at=et&turpis=ultrices&a=posuere&pede=cubilia&posuere=curae&nonummy=mauris&integer=viverra&non=diam&velit=vitae&donec=quam&diam=suspendisse&neque=potenti&vestibulum=nullam&eget=porttitor&vulputate=lacus&ut=at&ultrices=turpis&vel=donec&augue=posuere&vestibulum=metus&ante=vitae&ipsum=ipsum&primis=aliquam&in=non&faucibus=mauris&orci=morbi&luctus=non&et=lectus&ultrices=aliquam&posuere=sit&cubilia=amet&curae=diam&donec=in&pharetra=magna&magna=bibendum&vestibulum=imperdiet&aliquet=nullam&ultrices=orci&erat=pede&tortor=venenatis&sollicitudin=non&mi=sodales&sit=sed&amet=tincidunt&lobortis=eu&sapien=felis&sapien=fusce&non=posuere&mi=felis&integer=sed&ac=lacus",
        "timeZone": "11822-0873",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 7,
        "name": "Pestricke",
        "password": "83-934-0603",
        "email": "npestricke6@wikispaces.com",
        "avatar": "https://shutterfly.com/congue/etiam/justo/etiam/pretium/iaculis.xml?in=fermentum&ante=justo&vestibulum=nec&ante=condimentum&ipsum=neque&primis=sapien&in=placerat&faucibus=ante&orci=nulla&luctus=justo&et=aliquam&ultrices=quis&posuere=turpis&cubilia=eget&curae=elit&duis=sodales&faucibus=scelerisque&accumsan=mauris&odio=sit&curabitur=amet&convallis=eros&duis=suspendisse&consequat=accumsan&dui=tortor&nec=quis&nisi=turpis&volutpat=sed&eleifend=ante&donec=vivamus&ut=tortor&dolor=duis&morbi=mattis&vel=egestas&lectus=metus&in=aenean&quam=fermentum&fringilla=donec&rhoncus=ut&mauris=mauris&enim=eget&leo=massa&rhoncus=tempor&sed=convallis&vestibulum=nulla&sit=neque&amet=libero&cursus=convallis&id=eget&turpis=eleifend&integer=luctus&aliquet=ultricies&massa=eu&id=nibh&lobortis=quisque&convallis=id&tortor=justo&risus=sit&dapibus=amet&augue=sapien&vel=dignissim&accumsan=vestibulum&tellus=vestibulum&nisi=ante&eu=ipsum&orci=primis&mauris=in&lacinia=faucibus&sapien=orci&quis=luctus&libero=et&nullam=ultrices&sit=posuere&amet=cubilia&turpis=curae&elementum=nulla&ligula=dapibus&vehicula=dolor&consequat=vel&morbi=est&a=donec&ipsum=odio&integer=justo&a=sollicitudin&nibh=ut&in=suscipit&quis=a&justo=feugiat&maecenas=et&rhoncus=eros&aliquam=vestibulum&lacus=ac&morbi=est&quis=lacinia&tortor=nisi&id=venenatis&nulla=tristique&ultrices=fusce&aliquet=congue&maecenas=diam",
        "timeZone": "54868-4572",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 8,
        "name": "Berkely",
        "password": "96-933-5330",
        "email": "uberkely7@who.int",
        "avatar": "https://uol.com.br/sapien/urna/pretium/nisl/ut/volutpat/sapien.xml?a=eleifend&pede=pede&posuere=libero&nonummy=quis&integer=orci&non=nullam&velit=molestie&donec=nibh&diam=in&neque=lectus&vestibulum=pellentesque&eget=at&vulputate=nulla&ut=suspendisse&ultrices=potenti&vel=cras&augue=in&vestibulum=purus&ante=eu&ipsum=magna&primis=vulputate&in=luctus&faucibus=cum&orci=sociis&luctus=natoque&et=penatibus&ultrices=et&posuere=magnis&cubilia=dis&curae=parturient&donec=montes&pharetra=nascetur&magna=ridiculus&vestibulum=mus&aliquet=vivamus&ultrices=vestibulum&erat=sagittis&tortor=sapien&sollicitudin=cum&mi=sociis&sit=natoque&amet=penatibus&lobortis=et&sapien=magnis&sapien=dis&non=parturient&mi=montes&integer=nascetur&ac=ridiculus&neque=mus&duis=etiam&bibendum=vel&morbi=augue&non=vestibulum&quam=rutrum&nec=rutrum&dui=neque&luctus=aenean&rutrum=auctor&nulla=gravida&tellus=sem&in=praesent&sagittis=id&dui=massa&vel=id&nisl=nisl&duis=venenatis&ac=lacinia&nibh=aenean&fusce=sit&lacus=amet&purus=justo&aliquet=morbi&at=ut&feugiat=odio&non=cras&pretium=mi&quis=pede&lectus=malesuada&suspendisse=in&potenti=imperdiet&in=et&eleifend=commodo&quam=vulputate&a=justo&odio=in&in=blandit&hac=ultrices&habitasse=enim&platea=lorem&dictumst=ipsum&maecenas=dolor&ut=sit&massa=amet",
        "timeZone": "52797-020",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 9,
        "name": "Barensen",
        "password": "60-348-4164",
        "email": "sbarensen8@latimes.com",
        "avatar": "http://virginia.edu/integer.js?libero=porta&non=volutpat&mattis=erat&pulvinar=quisque&nulla=erat&pede=eros&ullamcorper=viverra&augue=eget",
        "timeZone": "65044-2417",
        "access_token": null,
        "isOnline": false
    }, {
        "id": 10,
        "name": "Skim",
        "password": "01-802-6375",
        "email": "pskim9@salon.com",
        "avatar": "http://pinterest.com/id/ornare/imperdiet.aspx?fusce=posuere&posuere=cubilia&felis=curae&sed=nulla&lacus=dapibus&morbi=dolor&sem=vel&mauris=est&laoreet=donec&ut=odio&rhoncus=justo&aliquet=sollicitudin&pulvinar=ut&sed=suscipit&nisl=a&nunc=feugiat&rhoncus=et&dui=eros&vel=vestibulum&sem=ac&sed=est&sagittis=lacinia&nam=nisi&congue=venenatis&risus=tristique&semper=fusce&porta=congue&volutpat=diam&quam=id&pede=ornare&lobortis=imperdiet&ligula=sapien&sit=urna&amet=pretium&eleifend=nisl&pede=ut&libero=volutpat&quis=sapien&orci=arcu&nullam=sed&molestie=augue&nibh=aliquam&in=erat&lectus=volutpat&pellentesque=in&at=congue&nulla=etiam&suspendisse=justo&potenti=etiam&cras=pretium&in=iaculis&purus=justo&eu=in&magna=hac&vulputate=habitasse&luctus=platea&cum=dictumst&sociis=etiam&natoque=faucibus&penatibus=cursus&et=urna&magnis=ut&dis=tellus&parturient=nulla&montes=ut&nascetur=erat&ridiculus=id&mus=mauris&vivamus=vulputate&vestibulum=elementum&sagittis=nullam&sapien=varius&cum=nulla&sociis=facilisi&natoque=cras&penatibus=non&et=velit&magnis=nec&dis=nisi&parturient=vulputate&montes=nonummy&nascetur=maecenas&ridiculus=tincidunt&mus=lacus&etiam=at",
        "timeZone": "55289-158",
        "access_token": null,
        "isOnline": false
    }]
}